10PinesLabs/secretPal

secretPal-backend/classes/production/secretPal-frontend/views/friendRelations.html, secretPal-backend/classes/production/secretPal-frontend/views/login.html, secretPal-backend/classes/production/secretPal-frontend/views/mail.html, secretPal-backend/classes/production/secretPal-frontend/views/main.html, secretPal-backend/classes/production/secretPal-frontend/views/profile.html, secretPal-backend/classes/production/secretPal-frontend/views/wishlist.html, secretPal-backend/classes/production/secretPal-frontend/views/workers.html, secretPal-backend/classes/test/secretPal-frontend/controllers/main.js, secretPal-backend/src/main/java/com/tenPines/application/SecretPalSystem.java, secretPal-backend/src/main/java/com/tenPines/application/service/WorkerService.java, secretPal-backend/src/main/java/com/tenPines/model/Credential.java, secretPal-backend/src/main/java/com/tenPines/model/Patova.java, secretPal-backend/src/main/java/com/tenPines/model/PatovaBobo.java, secretPal-backend/src/main/java/com/tenPines/model/User.java, secretPal-backend/src/main/java/com/tenPines/persistence/Repo.java, secretPal-backend/src/main/java/com/tenPines/persistence/UserRepository.java, secretPal-backend/src/main/java/com/tenPines/persistence/WorkerRepository.java, secretPal-backend/src/main/java/com/tenPines/restAPI/AuthController.java, secretPal-backend/src/main/java/com/tenPines/restAPI/SecurityToken.java, secretPal-backend/src/main/java/com/tenPines/restAPI/WorkerController.java, secretPal-backend/src/main/resources/application-local.properties, secretPal-backend/src/test/java/com/tenPines/model/PatovaTest.java, secretPal-frontend/app/index.html, secretPal-frontend/app/scripts/app.js, secretPal-frontend/app/scripts/controllers/login.js, secretPal-frontend/app/scripts/controllers/logout.js, secretPal-frontend/app/scripts/controllers/nav.js, secretPal-frontend/app/scripts/services/account.js, secretPal-frontend/app/scripts/services/token.js, secretPal-frontend/app/views/login.html
=> Login with internal credential

secretPal-backend/src/main/java/com/tenPines/application/SecretPalSystem.java, secretPal-backend/src/main/java/com/tenPines/application/service/MailerService.java, secretPal-backend/src/main/java/com/tenPines/restAPI/MailerController.java, secretPal-frontend/app/index.html, secretPal-frontend/app/scripts/app.js, secretPal-frontend/app/scripts/controllers/mailsFailure.js, secretPal-frontend/app/scripts/services/mailService.js, secretPal-frontend/app/views/mailsFailure.html
Tenés que ser Admin.
Admin -> Mensajes Rechazados
=> Failure mails view

secretPal-backend/src/main/java/com/tenPines/application/SecretPalSystem.java, secretPal-backend/src/main/java/com/tenPines/application/service/WorkerService.java, secretPal-backend/src/main/java/com/tenPines/persistence/WorkerRepository.java, secretPal-backend/src/main/java/com/tenPines/restAPI/FriendRelationController.java, secretPal-backend/src/main/java/com/tenPines/restAPI/WorkerController.java, secretPal-frontend/app/scripts/controllers/workers.js, secretPal-frontend/app/scripts/services/workerService.js
Hay que ingresar Siendo Admin. 
Admin -> Lista de Pinos
=> Muestra todos los pinos y refactors

secretPal-backend/src/main/java/com/tenPines/SecretPalConfig.java, secretPal-backend/src/main/java/com/tenPines/application/service/UserService.java, secretPal-backend/src/main/java/com/tenPines/application/service/WorkerService.java, secretPal-backend/src/main/java/com/tenPines/model/Credential.java, secretPal-backend/src/main/java/com/tenPines/model/InitializerLocalSystem.java, secretPal-backend/src/main/java/com/tenPines/model/NewUser.java, secretPal-backend/src/main/java/com/tenPines/model/PatovaBobo.java, secretPal-backend/src/main/java/com/tenPines/model/RegisterService.java, secretPal-backend/src/main/java/com/tenPines/model/SecurityGuardBobo.java, secretPal-backend/src/main/java/com/tenPines/model/User.java, secretPal-backend/src/main/java/com/tenPines/model/Worker.java, secretPal-backend/src/main/java/com/tenPines/persistence/UserRepository.java, secretPal-backend/src/main/java/com/tenPines/restAPI/AuthController.java, secretPal-backend/src/main/resources/mailTemplate.properties, secretPal-backend/src/test/java/com/tenPines/model/InitializerTest.java, secretPal-backend/src/test/java/com/tenPines/model/LoginTest.java, secretPal-backend/src/test/java/com/tenPines/model/PatovaTest.java, secretPal-backend/src/test/java/com/tenPines/model/RegisterTest.java, secretPal-frontend/app/index.html, secretPal-frontend/app/scripts/app.js, secretPal-frontend/app/scripts/controllers/main.js, secretPal-frontend/app/scripts/controllers/nav.js, secretPal-frontend/app/scripts/controllers/register.js, secretPal-frontend/app/scripts/services/account.js, secretPal-frontend/app/scripts/services/token.js, secretPal-frontend/app/views/login.html, secretPal-frontend/app/views/main.html, secretPal-frontend/app/views/register.html
-Se puede registrar con un mail de @10pines.com
-se puede loggear.
=> Register user

secretPal-frontend/app/views/workers.html
En vez de fecha de cumpleaños al crear un pino dice "fecha de nacimiento"
=> refactor en frontEnd -> resultado Demo

secretPal-backend/src/main/java/com/tenPines/application/service/UserService.java, secretPal-backend/src/main/java/com/tenPines/application/service/WorkerService.java, secretPal-backend/src/main/java/com/tenPines/model/NewUser.java, secretPal-backend/src/main/java/com/tenPines/model/RegisterService.java, secretPal-backend/src/main/java/com/tenPines/model/SecurityGuard.java, secretPal-backend/src/main/java/com/tenPines/restAPI/AuthController.java, secretPal-backend/src/test/java/com/tenPines/integration/SpringBaseTest.java, secretPal-backend/src/test/java/com/tenPines/model/PatovaTest.java, secretPal-backend/src/test/java/com/tenPines/model/RegisterTest.java
-Cuando quiero registrarme con UserName que ya fue usado, Excepcion
-Cuando quiero registrarme con Email que no corresponde a un Worker. Excepcion
-Cuando quiero registrarme con un Email que ya tiene un User asociado. Excepcion
-El resto de los casos debe permitir registrarme normalmente
=> Validate that email isnt in use

secretPal-backend/src/main/java/com/tenPines/application/SystemPalFacade.java, secretPal-backend/src/main/java/com/tenPines/application/service/GiftDefaultService.java, secretPal-backend/src/main/java/com/tenPines/errors/InvalidGiftDefaultException.java, secretPal-backend/src/main/java/com/tenPines/model/GiftDefault.java, secretPal-backend/src/main/java/com/tenPines/persistence/GiftDefaultRepository.java, secretPal-backend/src/main/java/com/tenPines/restAPI/AuthController.java, secretPal-backend/src/test/java/com/tenPines/integration/FacadeTest.java, secretPal-backend/src/test/java/com/tenPines/model/GiftTest.java, secretPal-frontend/app/views/profile.html
Persisto regalos default. 
Mockeado el front.
=> Gift default

secretPal-backend/src/main/java/com/tenPines/model/InitializerLocalSystem.java, secretPal-frontend/app/index.html, secretPal-frontend/app/scripts/app.js, secretPal-frontend/app/scripts/controllers/confirmationGift.js, secretPal-frontend/app/scripts/controllers/register.js, secretPal-frontend/app/scripts/services/token.js, secretPal-frontend/app/scripts/services/workerService.js, secretPal-frontend/app/styles/main.css, secretPal-frontend/app/views/confirmationGift.html, secretPal-frontend/app/views/mail.html, secretPal-frontend/app/views/register.html
-Se agrego el FrontEnd de "Marcar regalos recibidos en un worker"
---Se puede tildar y destildar, al destildar pedira un confirmacion, posiblemente se agregue un nuevo boton que sea para guardar los cambios o descartarlos.
=> Marcar regalos recibidos

secretPal-backend/src/main/java/com/tenPines/application/ReminderSystem.java, secretPal-backend/src/main/java/com/tenPines/application/service/FriendRelationService.java, secretPal-backend/src/main/java/com/tenPines/builder/FriendRelationMessageBuilder.java, secretPal-backend/src/main/java/com/tenPines/builder/HappyBithdayMessageBuilder.java, secretPal-backend/src/main/java/com/tenPines/builder/ReminderAproachTheBirthdayBuilder.java, secretPal-backend/src/main/java/com/tenPines/builder/ReminderBuilder.java, secretPal-backend/src/main/java/com/tenPines/mailer/UnsentMessage.java, secretPal-backend/src/main/java/com/tenPines/model/InitializerLocalSystem.java, secretPal-backend/src/main/resources/mailTemplate.properties, secretPal-backend/src/test/java/com/tenPines/mailer/ReminderSystemTest.java, secretPal-backend/src/test/java/com/tenPines/mailer/ScheduleMailerTest.java
=> Happy birthday mail

secretPal-backend/src/main/java/com/tenPines/application/ReminderSystem.java, secretPal-backend/src/main/java/com/tenPines/application/service/MailerService.java, secretPal-backend/src/main/java/com/tenPines/builder/FriendRelationMessageBuilder.java, secretPal-backend/src/main/java/com/tenPines/builder/ReminderAproachTheBirthdayBuilder.java, secretPal-backend/src/main/java/com/tenPines/builder/ReminderBuilder.java, secretPal-backend/src/main/java/com/tenPines/mailer/UnsentMessage.java, secretPal-backend/src/main/java/com/tenPines/model/EmailTemplate.java, secretPal-backend/src/main/java/com/tenPines/persistence/EmailTemplateRepository.java, secretPal-backend/src/main/java/com/tenPines/restAPI/MailerController.java, secretPal-backend/src/test/java/com/tenPines/mailer/ScheduleMailerTest.java
Es mas código que otra cosa.
Podés probar configurar el mail -> Ir a otro lado de la pag -> Volver y que se conserve lo que escribiste.
=> Persistance emails

secretPal-backend/src/main/java/com/tenPines/model/Worker.java, secretPal-backend/src/main/java/com/tenPines/restAPI/AuthController.java, secretPal-backend/src/test/java/com/tenPines/model/WorkerTest.java, secretPal-frontend/app/scripts/controllers/confirmationGift.js, secretPal-frontend/app/views/confirmationGift.html, secretPal-frontend/app/views/login.html, secretPal-frontend/app/views/register.html
probar que se guarda la fecha del momento en el que apretas el boton
=> Backend marcar cuando recibo regalo

secretPal-backend/src/main/java/com/tenPines/application/SystemPalFacade.java, secretPal-backend/src/main/java/com/tenPines/application/service/GiftDefaultService.java, secretPal-backend/src/main/java/com/tenPines/model/DefaultGift.java, secretPal-backend/src/main/java/com/tenPines/persistence/GiftDefaultRepository.java, secretPal-backend/src/main/java/com/tenPines/restAPI/AuthController.java, secretPal-backend/src/test/java/com/tenPines/integration/FacadeTest.java, secretPal-backend/src/test/java/com/tenPines/model/GiftTest.java, secretPal-frontend/app/scripts/controllers/giftDefault.js, secretPal-frontend/app/scripts/services/giftDefault.js, secretPal-frontend/app/views/giftDefault.html
Desde Admin
- Admin -> Configuración regalo default
- Modificar y cambia.
- Probar borrar y querer guardar todo vacío (va a decir que no se puede)
-Siempre tiene que haber regalo default, si no hay nada dice "$0, Nada"
=> Gift default final

secretPal-backend/src/main/java/com/tenPines/application/SystemPalFacade.java, secretPal-backend/src/main/java/com/tenPines/application/service/FriendRelationService.java, secretPal-backend/src/main/java/com/tenPines/persistence/FriendRelationRepository.java, secretPal-backend/src/main/java/com/tenPines/restAPI/FriendRelationController.java, secretPal-frontend/app/scripts/controllers/friendRelation.js, secretPal-frontend/app/scripts/services/friendRelationService.js, secretPal-frontend/app/styles/main.css, secretPal-frontend/app/views/friendRelations.html
Es mas que nada que ya no se rompe si reestableces las relaciones y se ve linda la vista. 
Mañana termino la lógica pero con esto le basta al buen PO.
=> Correcciones en relaciones entre pinos

secretPal-frontend/app/scripts/controllers/register.js, secretPal-frontend/app/views/register.html
Cuando te registras y las passwords son vacias te muestra un comentarioa que no coinciden y si llegases a confirmar igual, te insulta en un SweetAlert
=> validate passwords on register ok

secretPal-frontend/app/scripts/app.js, secretPal-frontend/app/scripts/controllers/friendRelation.js, secretPal-frontend/app/scripts/controllers/nav.js, secretPal-frontend/app/scripts/services/account.js
-Fijate de pegarle a las URL's de admin con un usuario que no es admin y deberia sacarte y no mostrarte nada.
=> No se puede entrar a las urls de admin sin ser admin (Fixed)

secretPal-backend/src/main/java/com/tenPines/application/SystemPalFacade.java, secretPal-backend/src/main/java/com/tenPines/application/service/FriendRelationService.java, secretPal-frontend/app/scripts/controllers/friendRelation.js, secretPal-frontend/app/scripts/services/friendRelationService.js, secretPal-frontend/app/views/friendRelations.html
Se crean la relacione automagicamente y se puede cambiar manual también con los disponibles.
=> Relations automatic

secretPal-frontend/app/index.html, secretPal-frontend/app/scripts/app.js, secretPal-frontend/app/scripts/controllers/giftDefault.js, secretPal-frontend/app/scripts/controllers/profile.js, secretPal-frontend/app/scripts/services/giftDefaultService.js, secretPal-frontend/app/styles/main.css, secretPal-frontend/app/views/giftDefault.html, secretPal-frontend/app/views/profile.html, secretPal-frontend/app/views/wishlist.html, secretPal-frontend/app/views/workers.html
- Se ve regalo default
-Se ve solo dia y mes de cumple
-Se  ocultan los datos propios del pino para mantener el secreto (podriamos ver a futuro hacerlo mas bonito con ayuda de Gaby)
=> Correcciones perfil

secretPal-frontend/app/index.html, secretPal-frontend/app/scripts/app.js, secretPal-frontend/app/scripts/controllers/gameStatus.js, secretPal-frontend/app/scripts/controllers/giftDefault.js, secretPal-frontend/app/scripts/controllers/profile.js, secretPal-frontend/app/scripts/services/gameStatusService.js, secretPal-frontend/app/scripts/services/giftDefaultService.js, secretPal-frontend/app/styles/main.css, secretPal-frontend/app/views/gameStatus.html, secretPal-frontend/app/views/giftDefault.html, secretPal-frontend/app/views/profile.html, secretPal-frontend/app/views/wishlist.html, secretPal-frontend/app/views/workers.html
Solo siendo Admin 
Admin -> Estado del juego
- Si paso el cumpleaños y no hay mails pendientes que incluyan el fullName del pino -> Se envió el mail de cumpleaños . 
- Si existe la relación y no hay mail pendiente para el pino que regala -> Se envió correctamente el mail de relación.
=> Game status

secretPal-backend/src/main/java/com/tenPines/application/SystemPalFacade.java, secretPal-backend/src/main/java/com/tenPines/application/service/MailerService.java, secretPal-backend/src/main/java/com/tenPines/mailer/UnsentMessage.java, secretPal-backend/src/main/java/com/tenPines/restAPI/MailerController.java, secretPal-frontend/app/scripts/controllers/mailsFailure.js, secretPal-frontend/app/scripts/services/mailService.js
Crear un mail en la base de datos
Desde Admin -> Mensajes rechazados
Hacer click en el botón Reenviar -> Ver que el mail llega y que no se muestra mas.
=> Resend mail

secretPal-frontend/app/index.html, secretPal-frontend/app/scripts/app.js, secretPal-frontend/app/scripts/controllers/ruleConfiguration.js, secretPal-frontend/app/views/ruleConfiguration.html
es la vista de la configuracion de las reglas. Aun no funciona pero para que lucas pueda ver y decidir si le parece bien hacerlo de esa forma.
=> vista de configuracion de reglas

secretPal-frontend/app/scripts/controllers/customParticipantRule.js, secretPal-frontend/app/scripts/controllers/giftDefault.js, secretPal-frontend/app/scripts/controllers/login.js, secretPal-frontend/app/scripts/controllers/mail.js, secretPal-frontend/app/scripts/controllers/profile.js, secretPal-frontend/app/scripts/controllers/workers.js
Quiero nombres de botones consistentes y en español
=> Botones consistentes

secretPal-backend/src/main/java/com/tenPines/application/ReminderSystem.java, secretPal-backend/src/test/java/com/tenPines/mailer/ScheduleMailerTest.java
*Visto que a varios les llegaron múltiples mail reminders, borro el scheduler hasta fixear este problema.*
=> Removing mail reminder until fix

secretPal-frontend/app/index.html, secretPal-frontend/bower.json
arreglado Sweet Alert desde master
=> arreglado SweetAlert

secretPal-frontend/app/scripts/controllers/guesses.js, secretPal-frontend/app/scripts/services/guessesService.js, secretPal-frontend/app/views/guesses.html
ya no tira error cuando todavia no adivinaste
=> bugfix de guesses

secretPal-frontend/app/scripts/controllers/friendRelation.js, secretPal-frontend/app/views/friendRelations.html
Ahora todos los cambios se guardan automáticamente.
=> Eliminado tick verde para confimar edición de relaciones entre pinos

secretPal-frontend/app/views/wishlist.html, secretPal-lib/src/main/resources/db/migration/all/V14__Changed_Wishlist_To_Text_Type.sql
Also agrego descripcion abajo del titulo because why not
=> Puedo agregar deseos de cualquier longitud sin que tire error

secretPal-lib/src/main/java/com/tenPines/application/service/CustomParticipantRuleService.java, secretPal-lib/src/main/java/com/tenPines/application/service/FriendRelationService.java, secretPal-lib/src/main/java/com/tenPines/application/service/ReplacerService.java, secretPal-lib/src/main/java/com/tenPines/restAPI/utils/PossibleRelationForFrontEnd.java, secretPal-lib/src/main/resources/mail-templates/assignation-html.html, secretPal-lib/src/main/resources/mail-templates/assignation-text.txt, secretPal-lib/src/test/java/com/tenPines/model/FriendRelationValidatorTest.java, secretPal-lib/src/test/java/com/tenPines/model/PossibleRelationForFrontEndTest.java
Se corrige performance de asignar posibles relaciones y el envio de mail al lockear relacion.
ADVERTENCIA: ES CODIGO HORRENDO PARA SALIR RAPIDO DEL APURO XQ CRASHEA EN PRODU
=> Send mail after lock
